apiVersion: v1
appVersion: "v1.42.1"
description: A customized Helm chart for the Meilisearch search engine
name: meilisearch
version: 0.99.0
icon: https://raw.githubusercontent.com/meilisearch/integration-guides/main/assets/logos/logo.svg
home: https://github.com/barskern/meilisearch-kubernetes/tree/main/charts/meilisearch
maintainers:
    - name: Ole Martin Ruud
      email: ole.martin.ruud@cern.ch
